import Image from "next/image";
import Header from "@/components/Header";
import Feed from "@/components/Feed";

export default function Home() {
  return (
    <div className="min-h-screen bg-dark">
      <Header />

      <main className="mx-auto max-w-2xl px-4 py-6">
        <div className="mb-6 rounded-xl border border-white/5 bg-card p-5">
          <div className="flex items-center gap-3">
            <Image
              src="https://pbs.twimg.com/profile_images/1437821373225717761/CzezIwWV_400x400.jpg"
              alt="Xiao Wang"
              width={48}
              height={48}
              className="h-12 w-12 rounded-full"
            />
            <div>
              <h2 className="font-semibold text-white">@xiaowang1984</h2>
              <p className="text-sm italic text-white/70">
                &ldquo;Just asking questions!&rdquo;
              </p>
              <p className="text-sm text-gray">
                Energy policy tweets, explained for everyone.
              </p>
            </div>
          </div>
        </div>

        <Feed />
      </main>

      <footer className="border-t border-white/5 py-6 text-center text-xs text-gray">
        <p>
          Xiao-nly Fans &mdash; Not affiliated with OnlyFans or @xiaowang1984.
          Tweets fetched via public RSS. Explanations generated by Claude.
        </p>
      </footer>
    </div>
  );
}
